version: '3'
services:

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg!lol!2021
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:5.1
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@lbaw.com
      PGADMIN_DEFAULT_PASSWORD: pg!lol!2021
    ports:
      - "4321:80"
    depends_on:
      - postgres
